// src/App.tsx
import { Head } from '@vueuse/head'
import { useGlobalLang } from './components/lang/useGlobalLang'

export function App() {
  const lang = useGlobalLang()

  return (
    <>
      <Head>
        {lang.isZh() ? <title>谢宇恒</title> : <title>Xie Yuheng</title>}
      </Head>

      <RouterView />
    </>
  )
}

// src/App.vue
<script setup lang="ts">
import { Head } from '@vueuse/head'
import { useGlobalLang } from './components/lang/useGlobalLang'

const lang = useGlobalLang()
</script>

<template>
  <Head>
    <title v-if="lang.isZh()">谢宇恒</title>
    <title v-else>Xie Yuheng</title>
  </Head>

  <RouterView />
</template>
